name: Docker Compose CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Node.js
              run: |
                  curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
                  sudo apt-get install -y nodejs

            - name: Set up Docker Compose
              run: |
                  sudo apt-get install -y docker-compose

            - name: Start services with docker-compose
              run: |
                  docker-compose -f docker-compose.yaml up -d
                  docker-compose -f docker-compose.yaml ps

            - name: Run tests against the services
              run: |
                  # Run some tests against the services
                  # For example, you could use curl or a testing framework

            - name: Stop services with docker-compose
              run: docker-compose -f docker-compose.yaml down
